apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secure-app

resources:
- namespace.yaml
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- external-secret.yaml

# `kustomize edit set image app=...` from CI rewrites this list.
# The deployment uses image name `app` as the key.
images:
- name: app
  newName: ghcr.io/wasimat404/secure-gitops-pipeline
  newTag: 02e195c
