apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-app
  namespace: secure-app
  # The ESO ClusterSecretStore is configured to bind to this SA when
  # authenticating to Vault via the kubernetes auth method.
